-- moar items
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41151, 'Robe of Eternal Autumn', '', 4, 1, 7, 1, 36392, 1, 0, 0, -1, -1, 163, 40, 20, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 45, 15, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41152, 'Royalist Leggings', '', 4, 2, 8, 1, 33273, 1, 0, 0, -1, -1, 223, 55, 7, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 35, 39, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41153, 'Winestained Bracers', '', 4, 2, 8, 1, 33275, 1, 0, 0, -1, -1, 99, 24, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 18, 20, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41154, 'Thalassian Sentinel Belt', '', 4, 3, 5, 1, 50642, 1, 0, 0, -1, -1, 106, 26, 6, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 20, 50, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41155, 'Lynx Sword', '', 2, 7, 1, 1, 22085, 1, 0, 0, -1, -1, 328, 82, 13, 3, 0, 0, 1, 1, 0, 5, 11, 2500, 0, 0, 35, 28, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41156, 'Mana Wyrm Cape', '', 4, 1, 7, 1, 23083, 1, 0, 0, -1, -1, 110, 27, 16, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41157, 'Vest of the Covenant', '', 4, 2, 8, 1, 40093, 1, 0, 0, -1, -1, 174, 43, 5, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 50, 45, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41158, 'Sash of Vengeance', '', 4, 1, 7, 1, 33388, 1, 0, 0, -1, -1, 13, 3, 6, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 16, 8, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, random_property, required_reputation_faction, required_reputation_rank) values (41159, 'Handguards of Vengeance', '', 4, 2, 8, 1, 33276, 1, 0, 0, -1, -1, 91, 22, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 18, 28, 0, 0, 8, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0);

-- fix
update item_template set display_id = 33268 where entry = 41113; -- royalist chain armor
-- use new displayid for AoS
update item_template set display_id = 68062, spellppmrate_2 = 1.5 where entry = 41076; -- Aspect of Seradane
-- buff axes
update item_template set spellppmrate_1 = 2 where entry = 19353; -- drake talon cleaver
update item_template set spellppmrate_1 = 1.4 where entry = 21856; -- Neretzek, The Blood Drinker
update item_template set spellppmrate_1 = 1 where entry = 12798; -- annihilator