INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_broadcast_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `box_broadcast_text`, `condition_id`) VALUES (59012, 1, 0, 'The young Moonfeather daughter in Forest Song requires your advice. She is struggling in her hippogryph handling training.', 0, 1, 1, 59016, 0, 59012, 0, 0, NULL, 0, 40799);
UPDATE `gossip_menu` SET `entry`=59016, `script_id`=0, `condition_id`=0 WHERE `text_id`=30077;
UPDATE `broadcast_text` SET `male_text`='Alleana? Ah, I see. She should have visited in person! Of course I will help.$B$B Tell her that it is all about apperance and mannerisms: Speaking to the fledglings not as a parent, not as a master, but as a friend and an equal. They will respect this approach, and only by earning their respect can she hope to bridge the gap between them.$B$BRemember that they are still wild creatures. Their strength and service they lend to us by their own will, not because we tame them or demand it of them.$B$BPlease return to Allie with this advice, and if you could also tell her... I often still press my lips to her letters at night. She really should come visit me for private tutelage someday.' WHERE  `entry`=30077;

INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_broadcast_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `box_broadcast_text`, `condition_id`) VALUES (59014, 1, 0, 'The young Moonfeather daughter in Forest Song requires your advice. She is struggling in her hippogryph handling training.', 0, 1, 1, 59017, 0, 59014, 0, 0, NULL, 0, 40799);
UPDATE `gossip_menu` SET `entry`=59017, `script_id`=0, `condition_id`=0 WHERE `text_id`=30079;
UPDATE `broadcast_text` SET `male_text`='Oh my word, how awful!$B$BAlleana is a Moonfeather, yes? I have every confidence she will find the method that works best for her. Every master handles the hippogryphs differently, as it is an intensely personal practice.$B$BThat said, I have heard the eastern reaches of our sacred forests are being ravaged much like the north. My condolences go out to her, and may Elune grant her strength. Perhaps taking a break to relax her mind would help.$B$BOne cannot hope to calm a wild beast while also being of an uncalm mind, after all.' WHERE  `entry`=30079;

UPDATE `gossip_menu` SET `entry`=59018, `script_id`=0, `condition_id`=0 WHERE `text_id`=30080;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_broadcast_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `box_broadcast_text`, `condition_id`) VALUES (59015, 1, 0, 'The young Moonfeather daughter in Forest Song requires your advice. She is struggling in her hippogryph handling training.', 0, 1, 1, 59018, 0, 59015, 0, 0, '', 0, 40799);
UPDATE `broadcast_text` SET `male_text`='<He looks up from replenishing the food for his charges and wipes the sweat from his brow with mucky, worn hands.>$B$BI am extremely busy right now performing my duties, $c. If Alleana wishes to follow in her siblings\'\' footsteps, she had best be prepared to put in the hours, days, years of blood, sweat, and tears to earn such an austere position.$B$BYou will excuse me.' WHERE  `entry`=30080;

UPDATE `gossip_menu` SET `entry`=59019, `script_id`=0, `condition_id`=0 WHERE `text_id`=30078;
INSERT INTO `gossip_menu_option` (`menu_id`, `id`, `option_icon`, `option_text`, `option_broadcast_text`, `option_id`, `npc_option_npcflag`, `action_menu_id`, `action_poi_id`, `action_script_id`, `box_coded`, `box_money`, `box_text`, `box_broadcast_text`, `condition_id`) VALUES (59013, 1, 0, 'The young Moonfeather daughter in Forest Song requires your advice. She is struggling in her hippogryph handling training.', 0, 1, 1, 59019, 0, 59013, 0, 0, NULL, 0, 40799);
UPDATE `broadcast_text` SET `male_text`='Yes, Alleana did write to me with her concerns a few months back. Those Moonfeathers are blessed in that they have a natural talent for communion with Elune’s favored creatures, who look upon them with respect. $B$BHmm... If they do not acknowledge her or her words, perhaps she has not yet gained the respect of the forest. The fledglings will know if she is one of their chosen by instinct alone. It has been too long since I visited the forests of our birth, but I am certain there must be a forest king or patriarch who would judge her as worthy.$B$BPerhaps she should seek out one of these creatures and earn their favor.' WHERE  `entry`=30078;
