-- more stuff from crite
-- Ironsun Citrine Ring (citrine) - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55141, 'Ironsun Citrine Ring', '', 4, 0, 1, 2, 23728, 2, 35, 0, -1, -1, 10000, 2500, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 6, 0, 0, 0, 0, 0, 0, 7, 6, 5, 5, 7677, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- Quartz Halo (quartz) - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55142, 'Quartz Halo', '', 4, 0, 1, 2, 24646, 2, 29, 0, -1, -1, 8000, 2000, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 34, 0, 25, 0, 0, 0, 0, 0, 0, 5, 6, 6, 4, 0, 0, 0);

-- Jade Harmony Circlet (jade) - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55143, 'Jade Harmony Circlet', '', 4, 0, 1, 2, 9833, 2, 32, 0, -1, -1, 9000, 2250, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 26, 0, 0, 0, 0, 0, 0, 4, 5, 3, 4, 6, 4, 0, 0, 0);

-- Goldfire Crystal Bracelet - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55144, 'Goldfire Crystal Bracelet', '', 4, 1, 7, 2, 28082, 2, 28, 0, -1, -1, 6000, 1500, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 25, 20, 0, 0, 33, 0, 25, 0, 0, 0, 0, 0, 0, 7, 5, 3, 5, 0, 0, 0);

-- Goldenshade Quartz Headpiece - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55145, 'Goldenshade Quartz Headpiece', '', 4, 1, 7, 2, 13585, 2, 33, 0, -1, -1, 12000, 3000, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 45, 41, 0, 0, 38, 0, 26, 0, 0, 0, 0, 0, 0, 3, 12, 7, 5, 9140, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- The Golden Goblet - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55146, 'The Golden Goblet', 'Use: Pour liquid gold over your target fearing it for 2 seconds and increasing your damage done to the target by 5% for 10 seconds.', 4, 0, 1, 2, 66212, 0, 33, 0, -1, -1, 12000, 3000, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 26, 0, 0, 0, 0, 0, 0, 7, 6, 0, 0, 0);

-- Powerful Citrine Pendant - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55147, 'Powerful Citrine Pendant', '', 4, 0, 1, 3, 15420, 2, 33, 0, -1, -1, 13500, 3375, 2, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 44, 0, 0, 0, 0, 0, 0, 6, 7, 5, 3, 9416, 1, 0, 0, 0, 0, 0, 0, 0, 0);

-- Scepter of Blossomed Jade - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55148, 'Scepter of Blossomed Jade', '', 2, 10, 1, 2, 66222, 2, 31, 0, -1, -1, 15000, 3750, 17, 1, 0, 0, 1, 1, 0, 77, 117, 3100, 0, 0, 85, 0, 0, 0, 36, 0, 26, 0, 0, 0, 0, 0, 0, 5, 13, 7, 7, 0, 0, 0);

-- Facetted Moonstone Brooch - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55210, 'Facetted Moonstone Brooch', '', 4, 0, 1, 2, 26571, 2, 35, 0, -1, -1, 12200, 3050, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 6, 0, 0, 0, 0, 0, 0, 6, 12, 0, 0, 0);

-- Obsidian Brooch - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55211, 'Obsidian Brooch', '', 4, 0, 1, 2, 16209, 2, 33, 0, -1, -1, 12000, 3000, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 38, 0, 26, 0, 0, 0, 0, 0, 0, 7, 11, 0, 0, 0);

-- Smoldering Brooch - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55212, 'Smoldering Brooch', '', 4, 0, 1, 2, 24730, 2, 38, 0, -1, -1, 13000, 3250, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 0, 7, 0, 0, 0, 0, 0, 0, 14027, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- Vitriol Brooch - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55213, 'Vitriol Brooch', '', 4, 0, 1, 2, 17957, 2, 39, 0, -1, -1, 13000, 3250, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 44, 0, 27, 0, 0, 0, 0, 0, 0, 5, 12, 0, 0, 0);


replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55274, 'Cloak of the Forgotten Dawn', '', 4, 1, 7, 4, 24928, 1, 60, 0, -1, -1, 299089, 59817, 16, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 63, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 5, 16, 21516, 1, 0, 0, 0, 0, 0, 21626, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55275, 'Slivers of Nullification', 'The fragments of the once powerful gem seem to be attracted to eachother. Remember to add the Arcane Reflection on use effect to the item when implemented.', 4, 0, 1, 4, 1231, 1, 60, 1, -1, -1, 362165, 90541, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 25, 7, 25, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55276, 'Forgotten Raven\'s Mallet', '', 2, 4, 1, 4, 66389, 1, 60, 0, -1, -1, 1038919, 207784, 13, 3, 0, 0, 1, 1, 0, 124, 229, 2700, 0, 0, 105, 125, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 7, 13, 13669, 1, 0, 0, 0, 0, 0, 45448, 1, 0, 0, 0, 0, 0, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55277, 'The End of All Ambitions', '', 2, 8, 1, 4, 5176, 1, 60, 0, -1, -1, 1199058, 239811, 17, 1, 0, 0, 1, 1, 0, 207, 385, 3500, 0, 0, 120, 0, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 4, 45, 7, 24, 7597, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55278, 'Ques\' Gauntlets of Precision', 'Will replace displayID with hunter T3.5 when added.', 4, 3, 5, 4, 9657, 1, 60, 0, -1, -1, 286552, 57310, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 50, 34193, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 7, 19, 5, 16, 15465, 1, 0, 0, -1, 0, -1, 15809, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55279, 'Branch of Resolute Defense', '', 4, 0, 1, 4, 6666, 1, 60, 0, -1, -1, 365411, 91352, 23, 6, 0, 0, 1, 1, 0, 0, 0, 0, 4, 0, 0, 125, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 3, 12, 7, 18, 13384, 1, 0, 0, -1, 0, -1, 13669, 1, 0, 0, 0, 0, 0, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55280, 'Boots of Elemental Fury', '', 4, 3, 5, 4, 6666, 1, 60, 1, 64, -1, 476544, 119136, 8, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 70, 360, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 5, 18, 7, 19, 14127, 1, 0, 0, -1, 0, -1, 23727, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55281, 'Gauntlets of Elemental Fury', '', 4, 3, 5, 4, 6666, 1, 60, 1, 64, -1, 299176, 74794, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 50, 328, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 5, 16, 7, 17, 24595, 1, 0, 0, -1, 0, -1, 21365, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55282, 'Boots of the Grand Crusader', '', 4, 4, 6, 4, 6666, 1, 60, 1, 2, -1, 298095, 74523, 8, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 75, 635, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 4, 16, 5, 17, 7, 16, 24595, 1, 0, 0, -1, 0, -1, 15464, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55283, 'Gauntlets of the Grand Crusader', '', 4, 4, 6, 4, 6666, 1, 60, 1, 2, -1, 202609, 50652, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 55, 582, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 4, 14, 5, 15, 7, 15, 9343, 1, 0, 0, -1, 0, -1, 7598, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55284, 'Dragunovi\'s Sash of Domination', '', 4, 1, 7, 4, 6666, 1, 60, 1, -1, -1, 209634, 52408, 6, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 35, 70, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 5, 14, 7, 12, 6, 15, 23729, 1, 0, 0, -1, 0, -1, 18049, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55285, 'Crite\'s Holy Hands', '', 4, 1, 7, 4, 6666, 1, 60, 1, -1, -1, 209811, 52452, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 35, 78, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 5, 19, 6, 22, 15696, 1, 0, 0, -1, 0, -1, 21626, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55286, 'Ring of Holy Light', '', 4, 0, 1, 4, 6666, 1, 60, 1, -1, -1, 454568, 113642, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 6, 19, 21518, 1, 0, 0, -1, 0, -1, 23729, 1, 0, 0, -1, 0, -1, 0, 0, 0);

replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, spellid_2, spelltrigger_2, spellcharges_2, spellppmrate_2, spellcooldown_2, spellcategory_2, spellcategorycooldown_2, random_property, required_reputation_faction, required_reputation_rank) values (55278, 'Ques\' Gauntlets of Precision', 'Will replace displayID with hunter T3.5 when added.', 4, 3, 5, 4, 9657, 1, 60, 0, -1, -1, 286552, 57310, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 50, 327, 0, 0, 83, 0, 65, 0, 0, 0, 0, 0, 0, 7, 19, 5, 16, 15465, 1, 0, 0, -1, 0, -1, 15809, 1, 0, 0, -1, 0, -1, 0, 0, 0);

update item_template set bonding = 2 where entry = 55032; -- Royal Robes of the Alteraci Princess
update item_template set bonding = 2, required_reputation_faction = 0, required_reputation_rank = 0 where entry = 55043; -- Harness of the High Thane
update item_template set bonding = 2, spelltrigger_1 = 1, spellppmrate_1 = 0 where entry = 55026; -- Alteraci Hunting Spear
update item_template set spelltrigger_1 = 1 where entry = 55040; -- Skyfall Mantle
update item_template set name = 'Valea\'s Alacrity' where entry = 55029; -- Isiden’s Alacrity
update item_template set name = 'Aliden\'s Prejudice' where entry = 55030; -- Aliden’s Prejudice
update item_template set name = 'Wildhammer Stormcaller' where entry = 55041 -- Gryphon Rider's Stormhammer