-- Grammar fixes:
UPDATE quest_template SET 
Details = 'Hail $N. Still looking for more work? I have a report that needs to reach Duke Nargelas in Glenshire.$BFret not, you won\'t be delivering it to his hands personally. All you must do is give this scroll to Deathguard Markus, he should be stationed right outside the church Duke Nargelas haunts.$B$BIt simply to let them know we\'ve decided to send adventurers into the Shadowfang Keep. Arugal mustn\'t be left alive. Getting to Glenshire shouldn\'t be that hard. You can either follow the path north or you can go back to Tirisfal Glades and reach it by traversing the Solliden Farmstead. Up to you.'
WHERE entry = 41364;
UPDATE quest_template SET 
Details = 'We do what the living cann- bah! I am piss tired of acting like nothing happened!$BCongratulations $N, you get to hear exactly -HOW- tired. It must be a thrill, right? Right?!$B$B<Basil sighs deeply.>$B$BI apologise, it seems something just clicked in my noggin just now. Feeling just a tad melancholic you see.$BI used to be a top-notch blacksmith at what\'s now known as the dreaded Scarlet Monastery. I remember the days I used to forge armor within the blessings of the Light.$B$BAnd nowadays, nowdays these maggots stare at me for even the mention of our former faith. Fools, all of them.$BAs luck has it, I was away from the Monastery the day that evil spawn Arthas scourged this entire city -- and now I am bound to forge my work around in the muck. Outrageous, I tell you, outrageous!$BMy apprentice Daghelm should be alive somewhere in the armory. The fool probably holds the journal I had on lightforge ingots - I want it back, even if you have to pry it from his dead cold fingers.'
WHERE entry = 41368;
-- Add item 41411 to loot table of 61982:
replace into creature_loot_template (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES
(61982, 41411, -100, 0, 1, 1, 0);
-- Item 70225 - necklace of redemption doesn't have the "neck" flag to it and can't be equipped.
update item_template set inventory_type = 2 where entry = 70225;
-- Make 61772 readable with the following text:
update item_template set page_text = 50723 where entry = 61772;
replace into `page_text` (`entry`, `text`, `next_page`) VALUES
(50723, 'I dedicated the entirety of my scholarly endeavours to the unraveling of the enigmas shrouded within the so-called Vorgendor, a Blood World nestled far in the Dark Beyond. This quest of mine led me through shadowed corridors of knowledge, where oft I found myself ensnared by the seductive whispers of Blood Magic. Yet, with steadfast resolve, I resisted its siren call, and now, I stand before thee, a humble chronicler, ready to unveil the saga of Vorgendor and its ancient myths.', 50724),
(50724, 'Vorgendor, a realm fraught with peril, is home to the bloodthirsty worgen, lupine beings consumed by an insatiable bloodlust. In their society, blood magic reigns supreme, wielded as a weapon to obliterate foes and subjugate the feeble. This dark art is a blight upon their culture, embraced in desperation to fend off the Emerald Flame, a sinister force that voraciously seeks to consume their world.', 50725),
(50725, 'Astute readers may find the term \'Emerald Flame\' vaguely familiar, for indeed, this malevolent force is none other than the Burning Legion, a mysterious power that once brought the orcs to our realm. The worgen of Vorgendor have waged an unending war against the Legion for years, a struggle they are gradually losing, despite resorting to magics as dark as those wielded by their adversaries.', 50726),
(50726, 'In my scholarly pursuit, I sought to unearth more than merely the blood magics that now dominate worgen society. I yearned to discover their origins, who they were before the blight of the Emerald Flame. Through the scant information salvaged from ancient scrolls and the visions that haunted my slumbers, I learned that in a time long forgotten, the Worgen held the Moon in reverence, akin to the elves of yore.', 50727),
(50727, 'They spoke of a blue moon that once danced across their skies, an entity they worshipped and adored as a divine goddess. This celestial bond intrigued me, for it bore an uncanny resemblance to our own Azeroth\'s blue moon, which emerges in the heavens during our most dire epochs. Could it be that the blue moon of Vorgendor and ours are one and the same?$B$BVenturing into the depths of Vorgendor, risking both my life and sanity, I beheld their heavens, yet the sight that greeted me was not of a tranquil blue, but a blood-red moon, casting a crimson pall over their world.', 50728),
(50728, 'Yet, all hope was not lost. Fortune allowed me to commune with one of their blood mages. The particulars of this rendezvous must remain shrouded in secrecy, for such knowledge must never be allowed to taint the hands of malevolence. Nevertheless, be assured, I was privy to a prophecy: the return of their Moon Goddess, heralding salvation. This prophecy foretold of a day when the Blue Moon would reappear, opening a gateway to a new realm, untouched by the Emerald Flame, where the worgen might thrive anew.', 50729),
(50729, 'They believed the Blue Moon would guide them to this sanctum, leaving me to ponder—a portentous thought—whether it might lead them to our world. Thus, I caution thee, beware the Blue Child, for it signals the advent of the worgen into our realm. This celestial harbinger, once a beacon of hope for a beleaguered race, now casts a shadow over our own fate. Should the prophecy come to pass, and the gateway between our worlds be rent asunder, we must prepare for the eventuality of their arrival.', 50730),
(50730, 'As I pen these words, my quill trembles, not out of fear, but with the weight of responsibility. The knowledge I have gleaned through my arduous journey—through forbidden tomes, whispered secrets of the arcane, and visions granted by the very fabric of magic itself—must serve as a beacon to those who would stand against the darkness.', 50731),
(50731, 'Let it be known that the worgen, though driven to desperation by their battle against the Emerald Flame, harbor within them the potential for both destruction and redemption. Their society, once illuminated by the gentle glow of the moon they venerated, now lies in the shadow of blood magic. Yet, the prophecy speaks of a rebirth, a chance for salvation not just for the worgen, but perhaps, for our world as well.', 50732),
(50732, 'In closing this tome, I implore thee, dear reader, to heed the lessons contained within these aged pages. The tale of Vorgendor is more than a mere chronicle of otherworldly beings and arcane mysteries; it is a warning. As we gaze upon the night sky, let us not forget the potential for worlds beyond our own to touch upon our fates. We must remain vigilant, for the cosmos is vast, and its secrets are myriad.', 50733),
(50733, 'And so, I lay down my quill, my life\'s work etched into the parchment of this tome. May these words endure as a testament to my journey into the dark beyond, a journey that has shown me the thin veil that separates our world from others, teeming with beings both majestic and terrifying. Beware the Blue Child, for its light may herald the dawn of a new age, or the twilight of our own.$B$BIn eternal pursuit of knowledge and in solemn warning,$B$BUr, Chronicler of the Dark Beyond, Guardian of Forgotten Lore.', 0);