-- crite stuff
-- Ebon Ring - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55316, 'Ebon Ring', '', 4, 0, 1, 2, 224, 2, 13, 0, -1, -1, 1000, 250, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 18, 0, 22, 0, 0, 0, 0, 0, 0, 7, 3, 0, 0, 0);

-- The King’s Conviction - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55317, 'The King\’s Conviction', '', 4, 0, 1, 2, 9837, 2, 15, 0, -1, -1, 1100, 275, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 2, 0, 0, 0, 0, 0, 0, 5, 3, 6, 2, 0, 0, 0);

-- SHadowfall Jewel - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55318, 'Shadowfall Jewel', '', 4, 0, 1, 2, 24022, 2, 18, 0, -1, -1, 1200, 300, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, 0, 23, 0, 0, 0, 0, 0, 0, 7, 3, 3, 3, 0, 0, 0);

-- Ocean's Wrath - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55319, 'Ocean\'s Wrath', '', 4, 0, 1, 2, 23728, 2, 21, 0, -1, -1, 1400, 350, 10, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 26, 0, 24, 0, 0, 0, 0, 0, 0, 4, 3, 3, 3, 5, 3, 0, 0, 0);

-- Dazzling Moonstone Band - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55320, 'Dazzling Moonstone Band', '', 4, 0, 1, 2, 9832, 2, 24, 0, -1, -1, 1600, 400, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 29, 0, 24, 0, 0, 0, 0, 0, 0, 6, 6, 0, 0, 0);

-- Harpy Talon Ring - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55321, 'Harpy Talon Ring', '', 4, 0, 1, 2, 26537, 2, 27, 0, -1, -1, 2000, 500, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 5, 0, 0, 0, 0, 0, 0, 3, 6, 7, 3, 0, 0, 0);

-- Centaur Hoof Circlet - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55322, 'Centaur Hoof Circlet', '', 4, 0, 1, 2, 32305, 2, 30, 0, -1, -1, 2200, 550, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 25, 0, 0, 0, 0, 0, 0, 7, 8, 0, 0, 0);

-- Ogre Bone Band - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55323, 'Ogre Bone Band', '', 4, 0, 1, 3, 23897, 2, 32, 0, -1, -1, 4000, 1000, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 37, 0, 44, 0, 0, 0, 0, 0, 0, 6, 8, 7, 4, 5, 4, 0, 0, 0);

-- Specter's Shade Ring - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55324, 'Specter\'s Shade Ring', '', 4, 0, 1, 2, 31905, 2, 34, 0, -1, -1, 3000, 750, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 39, 0, 26, 0, 0, 0, 0, 0, 0, 3, 7, 7, 4, 0, 0, 0);

-- Marine's Demise - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55325, 'Marine\'s Demise', '', 4, 0, 1, 2, 9833, 2, 36, 0, -1, -1, 3700, 925, 11, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 41, 0, 7, 0, 0, 0, 0, 0, 0, 7, 6, 9141, 1, 0, 0, -1, 0, -1, 0, 0, 0);


-- Serpent's Coil Staff - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55326, 'Serpent\'s Coil Staff', '', 2, 10, 1, 2, 20329, 2, 18, 0, -1, -1, 5000, 1250, 17, 1, 0, 0, 1, 1, 0, 32, 49, 2700, 0, 0, 75, 0, 0, 0, 23, 0, 23, 0, 0, 0, 0, 0, 0, 7, 5, 5, 5, 6, 3, 0, 0, 0);

-- Farraki Ceremony Totem - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55327, 'Farraki Ceremony Totem', '', 2, 10, 1, 3, 20360, 2, 26, 0, -1, -1, 7000, 1750, 17, 1, 0, 0, 1, 1, 0, 65, 99, 3200, 0, 0, 100, 0, 0, 0, 31, 0, 43, 0, 0, 0, 0, 0, 0, 5, 12, 4, 6, 21361, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- Sphinx's Wisdom Staff - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55328, 'Sphinx\'s Wisdom Staff', '', 2, 10, 1, 2, 28236, 2, 32, 0, -1, -1, 7700, 1925, 17, 1, 0, 0, 1, 1, 0, 61, 93, 3000, 0, 0, 85, 0, 0, 0, 37, 0, 26, 0, 0, 0, 0, 0, 0, 3, 14, 7, 3, 0, 0, 0);


-- Gloomweed Bindings - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55329, 'Gloomweed Bindings', '', 4, 1, 7, 2, 14736, 2, 14, 0, -1, -1, 800, 200, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 18, 14, 0, 0, 19, 0, 22, 0, 0, 0, 0, 0, 0, 3, 3, 7, 2, 0, 0, 0);

-- Hydrathorn Bracers - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55330, 'Hydrathorn Bracers', '', 4, 1, 7, 2, 28656, 2, 19, 0, -1, -1, 1025, 256, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 20, 16, 0, 0, 24, 0, 23, 0, 0, 0, 0, 0, 0, 5, 3, 7, 3, 6, 2, 0, 0, 0);

-- Blackrock Ironclamps - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, random_property, required_reputation_faction, required_reputation_rank) values (55331, 'Blackrock Ironclamps', '', 4, 1, 7, 3, 26055, 2, 26, 0, -1, -1, 2500, 625, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 30, 24, 0, 0, 31, 0, 43, 0, 0, 0, 0, 0, 0, 7, 9, 0, 0, 0);

-- Monastery Emberbrace - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55332, 'Monastery Emberbrace', '', 4, 1, 7, 2, 15410, 2, 32, 0, -1, -1, 2600, 650, 9, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 25, 21, 0, 0, 37, 0, 26, 0, 0, 0, 0, 0, 0, 5, 4, 4, 3, 9397, 1, 0, 0, 0, 0, 0, 0, 0, 0);


-- Shadowmoon Tome - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55333, 'Shadowmoon Tome', '', 4, 0, 1, 2, 23171, 2, 15, 0, -1, -1, 1200, 300, 23, 6, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 2, 0, 0, 0, 0, 0, 0, 7, 3, 5, 3, 0, 0, 0);

-- Fangclaw Relic - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, random_property, required_reputation_faction, required_reputation_rank) values (55334, 'Fangclaw Relic', '', 4, 0, 1, 3, 28487, 2, 22, 0, -1, -1, 1800, 450, 23, 6, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 27, 0, 42, 0, 0, 0, 0, 0, 0, 7, 5, 3, 5, 0, 0, 0);

-- Netherbane Spellbook - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55335, 'Netherbane Spellbook', '', 4, 0, 1, 2, 32515, 2, 30, 0, -1, -1, 2000, 500, 23, 6, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 35, 0, 25, 0, 0, 0, 0, 0, 0, 7, 5, 6, 3, 9395, 1, 0, 0, 0, 0, 0, 0, 0, 0);

-- Marine Root - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55336, 'Marine Root', '', 4, 0, 1, 2, 15424, 2, 38, 0, -1, -1, 4200, 1050, 23, 6, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 43, 0, 7, 0, 0, 0, 0, 0, 0, 5, 2, 21619, 1, 0, 0, -1, 0, -1, 0, 0, 0);


-- Mistwood Tiara - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, random_property, required_reputation_faction, required_reputation_rank) values (55337, 'Mistwood Tiara', '', 4, 1, 7, 2, 15336, 2, 19, 0, -1, -1, 2100, 525, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 40, 31, 0, 0, 24, 0, 23, 0, 0, 0, 0, 0, 0, 4, 5, 5, 5, 6, 4, 0, 0, 0);

-- Venomspire Diadem - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55338, 'Venomspire Diadem', '', 4, 1, 7, 3, 28131, 2, 27, 0, -1, -1, 5000, 1250, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 50, 40, 0, 0, 32, 0, 43, 0, 0, 0, 0, 0, 0, 7, 5, 21958, 1, 0, 0, -1, 0, -1, 0, 0, 0);

-- Bloodfire Circlet - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55339, 'Bloodfire Circlet', '', 4, 1, 7, 2, 28974, 2, 38, 0, -1, -1, 5300, 1325, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 45, 46, 0, 0, 43, 0, 7, 0, 0, 0, 0, 0, 0, 5, 14, 7, 5, 7689, 1, 0, 0, -1, 0, -1, 0, 0, 0);


-- Shadowforged Eye - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, stat_type2, stat_value2, stat_type3, stat_value3, stat_type4, stat_value4, stat_type5, stat_value5, random_property, required_reputation_faction, required_reputation_rank) values (55340, 'Shadowforged Eye', '', 4, 0, 1, 2, 16300, 2, 15, 1, -1, -1, 1100, 275, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 20, 0, 2, 0, 0, 0, 0, 0, 0, 7, 2, 4, 2, 3, 2, 5, 2, 6, 2, 0, 0, 0);

-- Totem of Self Preservation - 
replace into item_template (entry, name, description, class, subclass, material, quality, display_id, bonding, required_level, max_count, allowable_class, allowable_race, buy_price, sell_price, inventory_type, sheath, flags, extra_flags, buy_count, stackable, container_slots, dmg_min1, dmg_max1, delay, dmg_type1, ammo_type, max_durability, armor, block, bag_family, item_level, range_mod, disenchant_id, holy_res, fire_res, nature_res, frost_res, shadow_res, arcane_res, stat_type1, stat_value1, spellid_1, spelltrigger_1, spellcharges_1, spellppmrate_1, spellcooldown_1, spellcategory_1, spellcategorycooldown_1, random_property, required_reputation_faction, required_reputation_rank) values (55341, 'Totem of Self Preservation', '', 4, 0, 1, 3, 34144, 2, 25, 1, -1, -1, 3200, 800, 12, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 15, 0, 0, 30, 0, 42, 0, 0, 0, 6, 0, 0, 6, 5, 45420, 1, 0, 0, 0, 0, 0, 0, 0, 0);