update quest_template set nextquestinchain = 41325	 where entry = 41324;
-- An Echo From Beyond
delete from quest_template where entry = 41325;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (41324,41325,2,16,56,30,0,0,'An Echo From Beyond','Master did great by sending you to me. I am sure we can thank his clairvoyance for that, as I witnessed something truly frightening mere moments ago. You see to your right the abominable Dark Portal, legacy of the orcish invasion of your world? Master\'s suspicions regarding the portal\'s energy were true. Just before your arrival, a huge surge in power and a terrible, crushing force washed over the red sands of this desert. $B$BMy intuition tells me whatever lingers in front of it must be terrifyingly powerful. $N, please do not face it alone. Although the master has put your trust in you, what we are dealing with might very well be too much for you alone.','Face whatever is meddling at the Dark Portal and return to Kas\'tal overlooking the Blasted Lands.','Proceed with caution. We do not know what otherworldly horror might await us.','A shadowed specter? And it spoke of the enslavement of the Sanv tribe and Akh Z\'ador?! This is grim news, $R. For all our sakes, let me be wrong, but I fear the Harborage is in danger, grave danger!',0,0,0,0,0,0,0,0, 61984,1,0,0,0,0,0,0, 0,0, 0,37800,6300, 0,0,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (60850, 41325);
replace into creature_involvedrelation  (id, quest) values (60850, 41325);
update quest_template set nextquestinchain = 41326	 where entry = 41325;
update quest_template set type = 1					 where entry = 41325;

-- Manifested Oddities
delete from quest_template where entry = 41327;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (41326,41327,2,8,60,30,0,0,'Manifested Oddities','Much needs to be done, the Harborage is in disarray and many have been injured. You have to excuse me, as I need to tend to my brethren. While any help would be appreciated, I must insist on leaving this to us for now. You have done enough already and it\'d be rude to ask for more.$B$BBefore you depart however, Akh Z\'ador wishes to speak with you again about something urgent. You can find him outside. Enkil Toralar, friend, and good tidings to you.','Speak with Akh Z\'ador in the Harborage.','','$N, I thank you from the bottom of my heart for all you have done for the Harborage. Kas\'tal managed to contact me just in time. Any later and I fear for what might\'ve happened. Now, to what I wanted to talk with you about…$B$B<Akh Z\'ador presents a flawlessly round and shimmering teal crystal to you unlike anything you\'ve seen before.>$B$BWhat you see here is a pure draenethyst gemstone, one of the most rare commodities my people valued back on Draenor. Its status is akin to myth, although they are not the fairytale one might assume. Althoug it is just a theory, I assume this one was created between the clash of Tas\'dal\'s and my own rift magic. I want you to have it, as thanks - but also as a promise. The draenei of the Harborage will aid you if needed, for without you, we\'d be no more. Enkil Toralar, friend, and may the winds of the Twisting Nether be in your favor.',0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,25800,4300, 0,0,0,0,0,0,0,0, 0,0,0, 41385,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (91781, 41327);
replace into creature_involvedrelation  (id, quest) values (61987, 41327);
update quest_template set nextquestinchain = 41328	 where entry = 41327;

replace into item_template (entry, display_id, name, class, quality, flags, buy_count, allowable_class, allowable_race, item_level, stackable, spellcooldown_1, spellcategorycooldown_1, spellcooldown_2, spellcategorycooldown_2, bonding, description, page_text, material) values
(41385,7205,'Pure Draenethyst Gemstone',12,1,1,1,-1,-1,1,20,-1,-1,-1,-1,1,'',0,4);

update creature_template set phase_quest_id = 41326 where entry = 61987;

-- A Favor Asked
delete from quest_template where entry = 41328;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (41327,41328,2,8,60,30,0,1,'A Favor Asked','$N! A pleasure seeing you again. How have you been faring? We are still in the process of restoration, but the morale of most stays high. Some are still anxious of the uncertain future we might face.$B$BI have been looking into the pure draenethyst gemstone I gave you and I am certain I can reproduce one with the knowledge I gained from its creation. It will require an incredible amount of energy to replicate the process, but it will definitely be worth your efforts. Should you wish to have another gemstone, please bring me the following and I am more than happy to deliver it to you.','For Akh Z\'ador to create a Pure Draenethyst Gemstone, bring him the following. He awaits in the Harborage in the Swamp of Sorrows.','I\'ll be here whenever you need me.','An exhausting process, but here it is; another pure gemstone. Please, take good care of it.',8244,1,61673,5,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0, 41385,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (61987, 41328);
replace into creature_involvedrelation  (id, quest) values (61987, 41328);