-- To Rum it All - Light
delete from quest_template where entry = 41329;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41329,0,33,60,10,0,1,'To Rum it All - Light','','Bring 10 Rumsey Rum Light to \'Ale Saint\' Grida','Ahoy, captain! Managed to sneak a peak over me new recipe, have ye? You know ale\'s closer to me heart and I am happy to provide to the rest of the lads anytime. And I believe so would ye. This takes us to the real problem, cap\'n.$B$BSee, the ale\'s fine but the lads be getting restless. It be too warm outside for us to drink just ale all day! And blasted be the Sea Witch if we\'d ever work sober. So as the captain of this crew, you must assume responsibility! Bah, me tongue be dancing around me mouth too much.$B$B We need rum Cap\'n.','Aw, was this the best ye could get?',20709,10,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,0,0, 87,50,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (60460, 41329);
replace into creature_involvedrelation  (id, quest) values (60460, 41329);

-- To Rum it All - Light
delete from quest_template where entry = 41330;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41330,0,33,60,10,0,1,'To Rum it All - Dark','','','Ahoy, captain! Managed to sneak a peak over me new recipe, have ye? You know ale\'s closer to me heart and I am happy to provide to the rest of the lads anytime. And I believe so would ye. This takes us to the real problem, cap\'n.$B$BSee, the ale\'s fine but the lads be getting restless. It be too warm outside for us to drink just ale all day! And blasted be the Sea Witch if we\'d ever work sober. So as the captain of this crew, you must assume responsibility! Bah, me tongue be dancing around me mouth too much.$B$BWe need rum Cap\'n.','That\'s the good stuff! The lads be already licking they lips.',21114,10,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,0,0, 87,100,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (60460, 41330);
replace into creature_involvedrelation  (id, quest) values (60460, 41330);

-- To Rum it All - Black Label
delete from quest_template where entry = 41331;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41331,0,33,60,10,0,1,'To Rum it All - Black Label','','','Ahoy, captain! Managed to sneak a peak over me new recipe, have ye? You know ale\'s closer to me heart and I am happy to provide to the rest of the lads anytime. And I believe so would ye. This takes us to the real problem, cap\'n.$B$BSee, the ale\'s fine but the lads be getting restless. It be too warm outside for us to drink just ale all day! And blasted be the Sea Witch if we\'d ever work sober. So as the captain of this crew, you must assume responsibility! Bah, me tongue be dancing around me mouth too much.$B$BWe need rum Cap\'n.','Oho, now where\'d you get that? Something ye\'d toast at the table of the Pirate King! If there were one...',21151,10,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,0,0, 87,150,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (60460, 41331);
replace into creature_involvedrelation  (id, quest) values (60460, 41331);

-- To Rum it All - Volatile
delete from quest_template where entry = 41332;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41332,0,33,60,10,0,1,'To Rum it All - Volatile','','','Ahoy, captain! Managed to sneak a peak over me new recipe, have ye? You know ale\'s closer to me heart and I am happy to provide to the rest of the lads anytime. And I believe so would ye. This takes us to the real problem, cap\'n.$B$BSee, the ale\'s fine but the lads be getting restless. It be too warm outside for us to drink just ale all day! And blasted be the Sea Witch if we\'d ever work sober. So as the captain of this crew, you must assume responsibility! Bah, me tongue be dancing around me mouth too much.$B$BWe need rum Cap\'n.','Shiver me timbers! The damned thing feels like the kiss of a Siren.',9260,5,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,0,0, 87,200,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (60460, 41332);
replace into creature_involvedrelation  (id, quest) values (60460, 41332);