-- Blood of the Mountain Questline:
-- Gleaming Blood
delete from quest_template where entry = 41361;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41361,2,-371,50,50,0,0,'Gleaming Blood','<The unbearable fumes make it hard to see, but what you found on the simmering ground is a vibrant crystal, scalding to the touch. While gauging its value to be tremendously high, you dare not to try working on the gem, lacking the expertise to properly cut the stone. It seems you need to find someone who can teach you such skills.>','Find someone to teach you about the scalding gemstone.','Stranger, you better be here for a good reason.','Blood of the Mountain! Getting your hands on one of those beauties has been really difficult, ever since Thaurissan\'s loyalists took control over all mining operations in and around the Blackrock. And this one seems to be a special kind...',41407,1,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 41407,1, 0,26250,3750, 0,0,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into gameobject_questrelation		(id, quest) values (2020110, 41361);
replace into creature_involvedrelation	(id, quest) values (12944, 41361);
update quest_template set nextquestinchain = 41362	 where entry = 41361;
update quest_template set requiredskill		 = 750		 where entry = 41361;
update quest_template set requiredskillvalue = 300		 where entry = 41361;

REPLACE INTO `gameobject_template` (`entry`, `type`, `displayId`, `name`, `faction`, `flags`, `size`, `data0`, `data1`, `data2`, `data3`, `data4`, `data5`, `data6`, `data7`, `data8`, `data9`, `data10`, `data11`, `data12`, `data13`, `data14`, `data15`, `data16`, `data17`, `data18`, `data19`, `data20`, `data21`, `data22`, `data23`, `mingold`, `maxgold`, `phase_quest_id`, `script_name`) VALUES
(2020110, 2, 26165, 'Glimmering Shard', 0, 32, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, '');

replace into item_template (entry, display_id, name, class, quality, flags, buy_count, allowable_class, allowable_race, item_level, stackable, spellcooldown_1, spellcategorycooldown_1, spellcooldown_2, spellcategorycooldown_2, bonding, description, page_text, material) values
(41407,33448,'Glimmering Shard',12,1,2048,1,-1,-1,1,1,-1,-1,-1,-1,4,'',0,4);

-- To Cut A Heart
delete from quest_template where entry = 41362;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (41361,41362,2,-371,50,50,0,0,'To Cut A Heart','You are correct in your assumption; I indeed can teach you how to cut a Blood of the Mountain yourself. To do so however requires a set of reagents I do not have access to. This warehouse may be plentiful, but with all the machinations Thaurissan is planning, the good stuff runs dry.$B$BHere, bring me these materials and I will gladly show you the old Dark Iron art of cutting a Blood of the Mountain.','Bring Lokthos Darkbargainer the needed materials. He waits in the Grim Guzzler in the Blackrock Depths.','The Dark Iron pride themselves on their mastery over the mountain\'s body. Seldom has anyone else shown such expertise in manipulating Dark Iron ore and the countless unique gemstones found within its crust.','I appreciate the effort, $N. This was definitely not an easy task, yet you provided me with such quality materials in no time at all.$B$BGemstones like the Blood of the Mountain require an extraordinary amount of precision and patience. Just the tiniest bit of unnecessary pressure and the entire jewel cracks in two. Watch closely, for I have only one chance to teach you. You can keep the gemstone once I\'m done. See it as thanks for bringing me such a peculiar example of a gem.',7077,6,55248,1,55154,2,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,33250,4750, 0,0,0,0,0,0,0,0, 0,0,0, 61818,1,70209,1,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values (12944, 41362);
replace into creature_involvedrelation	(id, quest) values (12944, 41362);
update quest_template set requiredskill		 = 750	 where entry = 41362;
update quest_template set requiredskillvalue = 300	 where entry = 41362;

-- Wailing Caverns Quest
-- Rampant Weeds
delete from quest_template where entry = 41363;
replace into quest_template (prevquestid, entry, method, zoneorsort, questlevel, minlevel, questflags, specialflags, title, details, objectives, requestitemstext, offerrewardtext, reqitemid1, reqitemcount1, reqitemid2, reqitemcount2, reqitemid3, reqitemcount3, reqitemid4, reqitemcount4, reqcreatureorgoid1, reqcreatureorgocount1, reqcreatureorgoid2, reqcreatureorgocount2, reqcreatureorgoid3, reqcreatureorgocount3, reqcreatureorgoid4, reqcreatureorgocount4, srcitemid, srcitemcount, reworreqmoney, RewMoneyMaxLevel, rewxp, rewrepfaction1, rewrepvalue1,  rewrepfaction2, rewrepvalue2, rewrepfaction3, rewrepvalue3, rewrepfaction4, rewrepvalue4, rewspell, rewspellcast, completeemote, rewitemid1, rewitemcount1, rewitemid2, rewitemcount2, rewitemid3, rewitemcount3, rewitemid4, rewitemcount4, rewchoiceitemid1, rewchoiceitemcount1, rewchoiceitemid2, rewchoiceitemcount2, rewchoiceitemid3, rewchoiceitemcount3, rewchoiceitemid4, rewchoiceitemcount4,requiredminrepfaction,requiredminrepvalue,objectivetext1) values (0,41363,2,718,20,16,0,0,'Rampant Weeds','You might\'ve convened with my disciple Alanndrian already, she has taken it up herself to investigate the dangers crawling out of the Wailing Caverns, a cursed maze of caves in the Barrens south of Ashenvale.$B$BWhile noble - and certainly naive - Naralex\' foolishness caused irreparable damage to the balance of Kalimdor, most prominently discernible at the rampant growths sprouting from the stone labyrinth. Some of these plants began to move by themselves, a testament to the potential of Naralex\' involuntary powers. I wish to study these plants, so that I may devise a countermeasure with the Cenarion Circle.$B$BBring me enough samples of the most violent plants you can find within the Wailing Caverns and you will be just rewarded.','Thundris Windweaver in Auberdine needs samples of the Unnatural Overgrowths in the Wailing Caverns.','Be careful. Not only is this den of nightmares highly dangerous, but also your journey through Horde territory.','Intriguing. These samples radiate a magic not unfamiliar to me, on first glance I\'d even say they emanate druidic magic. Ofcourse, I shouldn\'t jump to conclusions. Further research within the Cenarion Circle will be needed. Surely their venerable druids can solve the origin of their volatile growth.$B$B$N, you have my appreciation. Please, take one of these as compensation for your troubles.',41408,8,0,0,0,0,0,0, 0,0,0,0,0,0,0,0, 0,0, 0,14000,2000, 69,100,0,0,0,0,0,0, 0,0,0, 0,0,0,0,0,0,0,0, 3827,3,1710,3,0,0,0,0, 0,0,'');

replace into creature_questrelation		(id, quest) values ( 3649, 41363);
replace into creature_involvedrelation	(id, quest) values ( 3649, 41363);
update quest_template set type = 81					 where entry = 41363;
update quest_template set requiredraces = 589		 where entry = 41363;

replace into item_template (entry, display_id, name, class, quality, flags, buy_count, allowable_class, allowable_race, item_level, stackable, spellcooldown_1, spellcategorycooldown_1, spellcooldown_2, spellcategorycooldown_2, bonding, description, page_text, material) values
(41408,19496,'Overgrowth Sample',12,1,2048,1,-1,-1,1,8,-1,-1,-1,-1,4,'',0,3);

REPLACE INTO `creature_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`) VALUES
(61964, 41408, -100, 0, 1, 1, 0);