-- Generated by "GenerateCameraMesh" program. Giperion 2020 - 2023 for Turtle project

DELETE FROM cinematic_waypoints WHERE cinematic = 164;

INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '0', '185', '-8336', '32', 'FlyByGoblin.m2_0');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '6000', '120', '-8101', '32', 'FlyByGoblin.m2_1');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '12000', '-17', '-8007', '69', 'FlyByGoblin.m2_2');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '19000', '-168', '-7824', '46', 'FlyByGoblin.m2_3');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '23000', '-207', '-7768', '47', 'FlyByGoblin.m2_4');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '32000', '-269', '-7605', '116', 'FlyByGoblin.m2_5');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '41000', '-242', '-7446', '112', 'FlyByGoblin.m2_6');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '59000', '-238', '-7233', '32', 'FlyByGoblin.m2_7');
INSERT INTO `cinematic_waypoints` (`cinematic`, `timer`, `position_x`, `position_y`, `position_z`, `comment`) VALUES('164', '62000', '-236', '-7202', '25.9', 'FlyByGoblin.m2_8');

